owner: telemetryforge
repo: status

skipDescriptionUpdate: true
skipTopicsUpdate: true

sites:
  - name: Main site
    url: https://telemetryforge.io
  - name: Documentation
    url: https://docs.telemetryforge.io
  - name: Fleet Manager
    url: https://manager.telemetryforge.io

status-website:
  cname: status.telemetryforge.io
  logoUrl: https://raw.githubusercontent.com/telemetryforge/status/main/assets/logo.png
  favicon: https://raw.githubusercontent.com/telemetryforge/status/main/assets/favicon-32x32.png
  name: Telemetry Forge Status
  introTitle: "**Telemetry Forge Status**: Real-time updates on our services."
  introMessage: "Check the status of our services and subscribe to updates."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# See https://upptime.js.org/docs/configuration
